name: Merge develop into m1
on:
  push:
    branches:
      - develop
jobs:
  mergeIntoDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: Merge to develop branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'm1'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
