name: Merge master into develop
on:
  push:
    branches:
      - master
jobs:
  mergeIntoDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to develop branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'develop'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  mergeDevelopIntoM1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref:  develop
      - name: Checkout to develop
      - uses: devmasx/merge-branch@v1.1.0
      - name: Merge to m1
        with:
          type: now
          target_branch: 'm1'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

