name: Merge master into develop
on:
  push:
    branches:
      - master
jobs:
  mergeIntoDevelop:
    runs-on: ubuntu-latest
    steps:
-name: Merge into develop
	run: |
	git fetch --all
	git checkout develop origin/develop
	git reset --hard origin/develop
	git pull origin master
	git push origin develop
